---
title: Ingreso al Sistema
---
sequenceDiagram
    actor Usuario
    participant Sistema

    Usuario->>Sistema: Ingresarsistema()
    Sistema-->>Usuario: mostrarLogin/Register()

    
    
